### ISSUE TITLE
Generate Swagger for dynamic Api Gateway

### ISSUE THREAD

**Issue by brunobertechini** [mauroservienti/designing-a-ui-for-microservices-demos#1]
Hi Mauro,

Congrats on this talk and demos. They are really awesome and explain it beautifully how to handle ui composition.

I was wondering if there are any ways to generate swagger endpoints (manually is feasible) to the composite approach.

This will make it easier for frontend apps using angular to use nswag or something to generate service proxies for composite apis.

I am doing a research on swashbuckle and nswag to check if we can dynamically add methods/operations in order to achieve this.

Any thoughts ?

Regards

Bruno

**Comment by mauroservienti** [comment]
Hey @brunobertechini thanks a lot. I never used swagger, reading about it it seems that there are options to generate a json document with swagger format metadata, this document will be queried by clients.
I’ll investigate.
.m
