### ISSUE TITLE
Authorization for each Service Api

### ISSUE THREAD

**Issue by brunobertechini** [mauroservienti/designing-a-ui-for-microservices-demos#2]
Hi Mauro,

One question came up these days and I would like to get in touch with you to hear your word.

Based on this implementation of UI composition, each service will "fill in" the view model based on route. Thats more than fine.

When it comes to authorization, and when I say authorization I mean, a given user have a permission to "READ Orders" for example.

Since the api of each service is exposed as REST as well, how do we handle authorization on each service? Should it even be done at all ?

Should ITOps (which does the routing composition handle it?)

For example we have Gateway01 and 02. Both have api exposed. Lets say ITOps handle the Authorization code to say that User A has permission to view orders.

Should this be a library (auth library) shared among all services (infrastructure concerns) and each one uses an authorization filter with a permission defined whithin the service boundary?

Can you shed some light on this ?

Thanks a lot

Bruno

**Comment by mauroservienti** [comment]
There is 2 part when it comes to authorization IMO @brunobertechini. 

## Root level authorization

For every request there is a logical owner, using your sample `Orders`, as a concept, are owned say by `Sales`. In this case if the user issuing the request is not authorized to access `Orders` I expect the Sales ViewModel Appender to throw. This can be done directly in the appender code or by plugging into the .NET Core authorization pipeline. I Prefer the latter. At deploy time `Sales` for example can deploy an authorization filter/request delegate that intercepts HTTP requests and blocks non-authorized ones.

## Leaf level authorization

A different, and slightly more complex, story has to be defined if you need to say something like:

> User Mauro can view `Orders` but cannot view `Prices`

This second scenario has to be handled in the appender code itself, the silently drop the price from the composed `ViewModel`. Finally the `View` needs to be aware that the price can be absent and react accordingly.

Thoughts?

**Comment by brunobertechini** [comment]
@mauroservienti thanks for your time answering this.

Yes it makes sense.

Of course the view must be aware of the authorization guidelines.

Thanks a lot

Bruno

**Comment by mauroservienti** [comment]
Yes, view has to aware of authorization guidelines.

Another option is to chose the same approach used by GraphQL: add special response statuses to the returned model.

It really depends on the authorization granularity. In the scenario in which you can specify authorization rules on the field level you could return a model such as:

```
{
   firstName: ...,
   lastName: ...,
   authorization: {
      firstName: {
         status: 403,
         message: ...,
      }
```

And so on, it’s obviously more verbose, but in .Net can probably be easily automated with using delegate handlers at the WebApi level.
